# Generated by Django 4.2.8 on 2023-12-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('idpais', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=5, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8)),
                ('fecha_nacimiento', models.CharField(max_length=100)),
                ('fecha_registro', models.CharField(max_length=100)),
                ('estado', models.BooleanField()),
            ],
        ),
    ]
